version: '2'
services:
    databox_notifier_mysql:
        build: database
        ports:
            - "3308:3306"

    databox_notifier:
        build: app
        links:
            - databox_notifier_mysql
        ports:
            - "5000:5000"
        environment:
            - MYSQL_ROOT_PASSWORD=databox
            - MYSQL_DATABASE=databox_notifications
            - MYSQL_USER=databox
            - MYSQL_PASSWORD=databox
